package com.model.pojo;
// Generated 15/10/2020 9:34:41 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GenPersonalEmpresa generated by hbm2java
 */
@Entity
@Table(name="gen_personal_empresa"
    ,schema="postgres"
)
public class GenPersonalEmpresa  implements java.io.Serializable {


     private int codigoPersonal;
     private GenTiposIdentificacion genTiposIdentificacion;
     private String primerApellido;
     private String segundoApellido;
     private String primerNombre;
     private String segundoNombre;
     private String numeroIdentificacion;
     private Character genero;
     private String mailPersonal;
     private String mailEmpresarial;
     private String telefonoContacto;
     private String telefonoEmergencia;
     private String direccion;
     private Character esActivo;
     private String usuarioIngreso;
     private Date fechaIngreso;
     private String usuarioModificacion;
     private Date fechaModificacion;

    public GenPersonalEmpresa() {
    }

	
    public GenPersonalEmpresa(int codigoPersonal) {
        this.codigoPersonal = codigoPersonal;
    }
    public GenPersonalEmpresa(int codigoPersonal, GenTiposIdentificacion genTiposIdentificacion, String primerApellido, String segundoApellido, String primerNombre, String segundoNombre, String numeroIdentificacion, Character genero, String mailPersonal, String mailEmpresarial, String telefonoContacto, String telefonoEmergencia, String direccion, Character esActivo, String usuarioIngreso, Date fechaIngreso, String usuarioModificacion, Date fechaModificacion) {
       this.codigoPersonal = codigoPersonal;
       this.genTiposIdentificacion = genTiposIdentificacion;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.numeroIdentificacion = numeroIdentificacion;
       this.genero = genero;
       this.mailPersonal = mailPersonal;
       this.mailEmpresarial = mailEmpresarial;
       this.telefonoContacto = telefonoContacto;
       this.telefonoEmergencia = telefonoEmergencia;
       this.direccion = direccion;
       this.esActivo = esActivo;
       this.usuarioIngreso = usuarioIngreso;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
    }
   
     @Id 

    
    @Column(name="codigo_personal", unique=true, nullable=false)
    public int getCodigoPersonal() {
        return this.codigoPersonal;
    }
    
    public void setCodigoPersonal(int codigoPersonal) {
        this.codigoPersonal = codigoPersonal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_tipo_identificacion")
    public GenTiposIdentificacion getGenTiposIdentificacion() {
        return this.genTiposIdentificacion;
    }
    
    public void setGenTiposIdentificacion(GenTiposIdentificacion genTiposIdentificacion) {
        this.genTiposIdentificacion = genTiposIdentificacion;
    }

    
    @Column(name="primer_apellido", length=50)
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }

    
    @Column(name="segundo_apellido", length=50)
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }

    
    @Column(name="primer_nombre", length=50)
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }

    
    @Column(name="segundo_nombre", length=50)
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }

    
    @Column(name="numero_identificacion", length=20)
    public String getNumeroIdentificacion() {
        return this.numeroIdentificacion;
    }
    
    public void setNumeroIdentificacion(String numeroIdentificacion) {
        this.numeroIdentificacion = numeroIdentificacion;
    }

    
    @Column(name="genero", length=1)
    public Character getGenero() {
        return this.genero;
    }
    
    public void setGenero(Character genero) {
        this.genero = genero;
    }

    
    @Column(name="mail_personal", length=100)
    public String getMailPersonal() {
        return this.mailPersonal;
    }
    
    public void setMailPersonal(String mailPersonal) {
        this.mailPersonal = mailPersonal;
    }

    
    @Column(name="mail_empresarial", length=100)
    public String getMailEmpresarial() {
        return this.mailEmpresarial;
    }
    
    public void setMailEmpresarial(String mailEmpresarial) {
        this.mailEmpresarial = mailEmpresarial;
    }

    
    @Column(name="telefono_contacto", length=20)
    public String getTelefonoContacto() {
        return this.telefonoContacto;
    }
    
    public void setTelefonoContacto(String telefonoContacto) {
        this.telefonoContacto = telefonoContacto;
    }

    
    @Column(name="telefono_emergencia", length=20)
    public String getTelefonoEmergencia() {
        return this.telefonoEmergencia;
    }
    
    public void setTelefonoEmergencia(String telefonoEmergencia) {
        this.telefonoEmergencia = telefonoEmergencia;
    }

    
    @Column(name="direccion", length=500)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="es_activo", length=1)
    public Character getEsActivo() {
        return this.esActivo;
    }
    
    public void setEsActivo(Character esActivo) {
        this.esActivo = esActivo;
    }

    
    @Column(name="usuario_ingreso", length=100)
    public String getUsuarioIngreso() {
        return this.usuarioIngreso;
    }
    
    public void setUsuarioIngreso(String usuarioIngreso) {
        this.usuarioIngreso = usuarioIngreso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso", length=29)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="usuario_modificacion", length=100)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modificacion", length=29)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


