package com.model.pojo;
// Generated 15/10/2020 9:34:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GenTiposIdentificacion generated by hbm2java
 */
@Entity
@Table(name="gen_tipos_identificacion"
    ,schema="postgres"
)
public class GenTiposIdentificacion  implements java.io.Serializable {


     private int codigoTipoIdentificacion;
     private String nombre;
     private String descripcion;
     private Character esActivo;
     private String usuarioIngreso;
     private Date fechaIngreso;
     private String usuarioModificacion;
     private Date fechaModificacion;
     private Set genPersonalEmpresas = new HashSet(0);

    public GenTiposIdentificacion() {
    }

	
    public GenTiposIdentificacion(int codigoTipoIdentificacion) {
        this.codigoTipoIdentificacion = codigoTipoIdentificacion;
    }
    public GenTiposIdentificacion(int codigoTipoIdentificacion, String nombre, String descripcion, Character esActivo, String usuarioIngreso, Date fechaIngreso, String usuarioModificacion, Date fechaModificacion, Set genPersonalEmpresas) {
       this.codigoTipoIdentificacion = codigoTipoIdentificacion;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.esActivo = esActivo;
       this.usuarioIngreso = usuarioIngreso;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
       this.genPersonalEmpresas = genPersonalEmpresas;
    }
   
     @Id 

    
    @Column(name="codigo_tipo_identificacion", unique=true, nullable=false)
    public int getCodigoTipoIdentificacion() {
        return this.codigoTipoIdentificacion;
    }
    
    public void setCodigoTipoIdentificacion(int codigoTipoIdentificacion) {
        this.codigoTipoIdentificacion = codigoTipoIdentificacion;
    }

    
    @Column(name="nombre", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="es_activo", length=1)
    public Character getEsActivo() {
        return this.esActivo;
    }
    
    public void setEsActivo(Character esActivo) {
        this.esActivo = esActivo;
    }

    
    @Column(name="usuario_ingreso", length=100)
    public String getUsuarioIngreso() {
        return this.usuarioIngreso;
    }
    
    public void setUsuarioIngreso(String usuarioIngreso) {
        this.usuarioIngreso = usuarioIngreso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso", length=29)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="usuario_modificacion", length=100)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modificacion", length=29)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="genTiposIdentificacion")
    public Set getGenPersonalEmpresas() {
        return this.genPersonalEmpresas;
    }
    
    public void setGenPersonalEmpresas(Set genPersonalEmpresas) {
        this.genPersonalEmpresas = genPersonalEmpresas;
    }




}


