package com.model.pojo;
// Generated 15/10/2020 9:34:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TktEstadosTicket generated by hbm2java
 */
@Entity
@Table(name="tkt_estados_ticket"
    ,schema="postgres"
)
public class TktEstadosTicket  implements java.io.Serializable {


     private int codigoEstado;
     private String nombre;
     private String descripcion;
     private String nemonico;
     private Character esActivo;
     private String usuarioIngreso;
     private Date fechaIngreso;
     private String usuarioModificacion;
     private Date fechaModificacion;
     private Set tktTicketses = new HashSet(0);

    public TktEstadosTicket() {
    }

	
    public TktEstadosTicket(int codigoEstado) {
        this.codigoEstado = codigoEstado;
    }
    public TktEstadosTicket(int codigoEstado, String nombre, String descripcion, String nemonico, Character esActivo, String usuarioIngreso, Date fechaIngreso, String usuarioModificacion, Date fechaModificacion, Set tktTicketses) {
       this.codigoEstado = codigoEstado;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.nemonico = nemonico;
       this.esActivo = esActivo;
       this.usuarioIngreso = usuarioIngreso;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
       this.tktTicketses = tktTicketses;
    }
   
     @Id 

    
    @Column(name="codigo_estado", unique=true, nullable=false)
    public int getCodigoEstado() {
        return this.codigoEstado;
    }
    
    public void setCodigoEstado(int codigoEstado) {
        this.codigoEstado = codigoEstado;
    }

    
    @Column(name="nombre", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="nemonico", length=20)
    public String getNemonico() {
        return this.nemonico;
    }
    
    public void setNemonico(String nemonico) {
        this.nemonico = nemonico;
    }

    
    @Column(name="es_activo", length=1)
    public Character getEsActivo() {
        return this.esActivo;
    }
    
    public void setEsActivo(Character esActivo) {
        this.esActivo = esActivo;
    }

    
    @Column(name="usuario_ingreso", length=100)
    public String getUsuarioIngreso() {
        return this.usuarioIngreso;
    }
    
    public void setUsuarioIngreso(String usuarioIngreso) {
        this.usuarioIngreso = usuarioIngreso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso", length=29)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="usuario_modificacion", length=100)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modificacion", length=29)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tktEstadosTicket")
    public Set getTktTicketses() {
        return this.tktTicketses;
    }
    
    public void setTktTicketses(Set tktTicketses) {
        this.tktTicketses = tktTicketses;
    }




}


