package com.model.pojo;
// Generated 15/10/2020 9:34:41 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TktTickets generated by hbm2java
 */
@Entity
@Table(name="tkt_tickets"
    ,schema="postgres"
)
public class TktTickets  implements java.io.Serializable {


     private int codigoTicket;
     private GenPersonalEmpresa genPersonalEmpresa;
     private TktEstadosTicket tktEstadosTicket;
     private TktPrioridadTicket tktPrioridadTicket;
     private String comentarios;
     private Date fechaEmision;
     private Character esActivo;
     private String usuarioIngreso;
     private Date fechaIngreso;
     private String usuarioModificacion;
     private Date fechaModificacion;

    public TktTickets() {
    }

	
    public TktTickets(int codigoTicket) {
        this.codigoTicket = codigoTicket;
    }
    public TktTickets(int codigoTicket, GenPersonalEmpresa genPersonalEmpresa, TktEstadosTicket tktEstadosTicket, TktPrioridadTicket tktPrioridadTicket, Integer codigoPersonal, String comentarios, Date fechaEmision, Character esActivo, String usuarioIngreso, Date fechaIngreso, String usuarioModificacion, Date fechaModificacion) {
       this.codigoTicket = codigoTicket;
       this.genPersonalEmpresa = genPersonalEmpresa;
       this.tktEstadosTicket = tktEstadosTicket;
       this.tktPrioridadTicket = tktPrioridadTicket;
       this.comentarios = comentarios;
       this.fechaEmision = fechaEmision;
       this.esActivo = esActivo;
       this.usuarioIngreso = usuarioIngreso;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
    }
   
     @Id 

    
    @Column(name="codigo_ticket", unique=true, nullable=false)
    public int getCodigoTicket() {
        return this.codigoTicket;
    }
    
    public void setCodigoTicket(int codigoTicket) {
        this.codigoTicket = codigoTicket;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_estado")
    public TktEstadosTicket getTktEstadosTicket() {
        return this.tktEstadosTicket;
    }
    
    public void setTktEstadosTicket(TktEstadosTicket tktEstadosTicket) {
        this.tktEstadosTicket = tktEstadosTicket;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_prioridad")
    public TktPrioridadTicket getTktPrioridadTicket() {
        return this.tktPrioridadTicket;
    }
    
    public void setTktPrioridadTicket(TktPrioridadTicket tktPrioridadTicket) {
        this.tktPrioridadTicket = tktPrioridadTicket;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_personal")
    public GenPersonalEmpresa getGenPersonalEmpresa() {
        return this.genPersonalEmpresa;
    }
    
    public void setGenPersonalEmpresa(GenPersonalEmpresa genPersonalEmpresa) {
        this.genPersonalEmpresa = genPersonalEmpresa;
    }

    
    @Column(name="comentarios", length=500)
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_emision", length=29)
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    
    @Column(name="es_activo", length=1)
    public Character getEsActivo() {
        return this.esActivo;
    }
    
    public void setEsActivo(Character esActivo) {
        this.esActivo = esActivo;
    }

    
    @Column(name="usuario_ingreso", length=100)
    public String getUsuarioIngreso() {
        return this.usuarioIngreso;
    }
    
    public void setUsuarioIngreso(String usuarioIngreso) {
        this.usuarioIngreso = usuarioIngreso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso", length=29)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    
    @Column(name="usuario_modificacion", length=100)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modificacion", length=29)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


